import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser } from "@/lib/isAdmin";
import { getOrCreatePersonalWorkspace } from "@/lib/automation/workspace";
import { validateWorkflowDefinition } from "@/lib/automation/schema";
import { audit } from "@/lib/automation/persistence";

export const runtime = "nodejs";
async function context(params) { const supabase = await createClient(); const { user } = await getCurrentUser(supabase); if (!user) return { error: NextResponse.json({ error: "Yetkisiz" }, { status: 401 }) }; const workspace = await getOrCreatePersonalWorkspace(user); const { workflowId } = await params; return { supabase, user, workspace, workflowId }; }
export async function GET(_request, { params }) { try { const ctx = await context(params); if (ctx.error) return ctx.error; const { data, error } = await ctx.supabase.from("workflows").select("*").eq("id", ctx.workflowId).eq("workspace_id", ctx.workspace.id).is("deleted_at", null).single(); if (error) return NextResponse.json({ error: "Workflow bulunamadı." }, { status: 404 }); return NextResponse.json({ workflow: data }); } catch (error) { return NextResponse.json({ error: error.message }, { status: 500 }); } }
export async function PATCH(request, { params }) { try { const ctx = await context(params); if (ctx.error) return ctx.error; const body = await request.json(); const definition = validateWorkflowDefinition(body.definition); const { data, error } = await ctx.supabase.from("workflows").update({ name: String(body.name || "İsimsiz workflow").slice(0, 120), description: String(body.description || "").slice(0, 500), draft_definition: definition, updated_at: new Date().toISOString() }).eq("id", ctx.workflowId).eq("workspace_id", ctx.workspace.id).select().single(); if (error) throw error; await audit({ workspaceId: ctx.workspace.id, actorId: ctx.user.id, action: "workflow.updated", entityType: "workflow", entityId: data.id }); return NextResponse.json({ workflow: data }); } catch (error) { return NextResponse.json({ error: error.message || "Workflow kaydedilemedi." }, { status: 400 }); } }
export async function DELETE(_request, { params }) { try { const ctx = await context(params); if (ctx.error) return ctx.error; const { error } = await ctx.supabase.from("workflows").update({ deleted_at: new Date().toISOString(), status: "archived" }).eq("id", ctx.workflowId).eq("workspace_id", ctx.workspace.id); if (error) throw error; await audit({ workspaceId: ctx.workspace.id, actorId: ctx.user.id, action: "workflow.archived", entityType: "workflow", entityId: ctx.workflowId }); return new NextResponse(null, { status: 204 }); } catch (error) { return NextResponse.json({ error: error.message }, { status: 500 }); } }
