"use client";
import { useEffect, useState } from "react";

export default function SocialPage() {
  const [items, setItems] = useState([]); const [title, setTitle] = useState(""); const [platform, setPlatform] = useState("x"); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/social/content"); const data = await response.json(); if (response.ok) setItems(data.content); else setError(data.error); }
  useEffect(() => { const timer = setTimeout(() => { load(); }, 0); return () => clearTimeout(timer); }, []);
  async function create(event) { event.preventDefault(); const response = await fetch("/api/social/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ platform, title, format: "post", body: { text: title } }) }); const data = await response.json(); if (!response.ok) return setError(data.error); setTitle(""); setItems((current) => [data.content, ...current]); }
  return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Social OS</p><h1 className="mt-1 text-2xl font-semibold text-zinc-900 dark:text-zinc-50">İçerik kuyruğu</h1><p className="mt-1 text-sm text-zinc-500">Taslakları oluşturun; bağlantı yoksa yayın durumu asla bağlı görünmez.</p></header><form onSubmit={create} className="flex gap-2 rounded-xl border border-zinc-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900"><select value={platform} onChange={(e) => setPlatform(e.target.value)} className="rounded-lg border border-zinc-200 px-2 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="x">X</option><option value="instagram">Instagram</option></select><input value={title} onChange={(e) => setTitle(e.target.value)} required placeholder="İçerik fikri veya taslağı" className="min-w-0 flex-1 rounded-lg border border-zinc-200 px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"/><button className="rounded-lg bg-zinc-900 px-4 text-sm font-medium text-white dark:bg-zinc-100 dark:text-zinc-900">Taslak ekle</button></form>{error && <p className="text-sm text-rose-600">{error}</p>}<div className="grid gap-3 sm:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex justify-between text-xs text-zinc-500"><span>{item.platform}</span><span>{item.status}</span></div><p className="mt-3 text-sm font-medium text-zinc-900 dark:text-zinc-50">{item.title || "İsimsiz içerik"}</p></article>)}</div></div>;
}
